title: Hendrik Johann Schmidt
#logo: ![Photos of my hobbies](https://raw.githubusercontent.com/DarthvaderJouPa/DarthvaderJouPa.github.io/main/Images/PersonalPhoto.jpg "Photo of me")  
#description:
#show_downloads: true
theme: jekyll-theme-minimal
